-- ════════════════════════════════════════════════════════════════
-- 20 · Refugios — nuevas necesidades
--
-- Añade valores al enum shelter_need. Solo ADD VALUE (no se usan en esta
-- misma migración), seguro dentro de la transacción de `supabase db push`.
-- ('agua' ya existía.)
-- ════════════════════════════════════════════════════════════════

-- [ya incluido en el CREATE TYPE] alter type public.shelter_need add value if not exists 'perrarina';
-- [ya incluido en el CREATE TYPE] alter type public.shelter_need add value if not exists 'gatarina';
-- [ya incluido en el CREATE TYPE] alter type public.shelter_need add value if not exists 'correas';
-- [ya incluido en el CREATE TYPE] alter type public.shelter_need add value if not exists 'kennels';
