-- ════════════════════════════════════════════════════════════════
-- 25 · Refugios — más necesidades (insumos y enseres)
--
-- Solo ADD VALUE (no se usan en esta misma migración), seguro dentro de
-- la transacción de `supabase db push`.
-- ════════════════════════════════════════════════════════════════

-- [ya incluido en el CREATE TYPE] alter type public.shelter_need add value if not exists 'arena_gatos';
-- [ya incluido en el CREATE TYPE] alter type public.shelter_need add value if not exists 'productos_limpieza';
-- [ya incluido en el CREATE TYPE] alter type public.shelter_need add value if not exists 'camas';
-- [ya incluido en el CREATE TYPE] alter type public.shelter_need add value if not exists 'accesorios';
